### PR TITLE
fix html layout of shipment summary and settings and fix searching in woo orders overview

### LINKED ISSUE #359: Bug V4.0.1: Zoeken in bestellingen geeft foutmelding
Wanneer plugin is geactiveerd en je zoekt/filtert in de bestellingenlijst, wordt de volgende foutmelding weergeven. 

414 Request-URI Too Long 2020-07-24 13-46-39\

Wanneer je de plugin deactiveert, komt deze foutmelding niet tevoorschijn.

### PR DESCRIPTION
**Pull request by RichardPerdaan**
Fixes #359

### CODE REVIEW

**Comment by RichardPerdaan** [comment]
#359 https://github.com/myparcelnl/woocommerce/issues/359

File: includes/admin/class-wcmp-admin.php [hunk 1]
```diff
@@ -372,6 +372,28 @@ class="wcmp__offset-dialog__icon"/>
...
+    public function ajaxGetShipmentOptions(): void
+    {
+        // Order is used in views/html-order-shipment-options.php
+        $order = wc_get_order((int) $_POST['orderId']);
+
+        include('views/html-order-shipment-options.php');
+
+        die();
+    }
+
```
Comment (EdieLemoine) [inline includes/admin/class-wcmp-admin.php:395]: enter te veel

Comment (RichardPerdaan) [reply includes/admin/class-wcmp-admin.php:395]: done
