### PR TITLE
fix: prevent external translations

### LINKED ISSUE #872: Dutch language file corrupt
### Plugin version

4.13.2

### WooCommerce version

6.8.2

### WordPress version

6.0.1

### PHP version

7.4

### What went wrong?

Dutch language no longer works good since this morning’s language update.

If you put back the 4.13.2 .mo and .po file in wp-content/languages/plugins it works again, if you update the language file in wp-admin/update-core.php its corrupt again.

### Reproduction steps

1. admin/update-core.php
2. Click on update language 
3. See Dutch language is corrupt in wp-admin/admin.php?page=wcmp_settings

### Relevant log output

_No response_

### Additional context
https://snipboard.io/RAtWBy.jpg

### PR DESCRIPTION
**Pull request by joerivanveen**
Resolves #872

### CODE REVIEW

File: woocommerce-myparcel.php [hunk 1]
```diff
@@ -143,26 +143,12 @@ private function useStagingEnvironment(): void
...
-             *        - WP_LANG_DIR/plugins/woocommerce-myparcel-LOCALE.mo
-             */
-            load_textdomain(
-                self::DOMAIN,
-                $dir . 'woocommerce-myparcel/' . self::DOMAIN . '-' . $locale . '.mo'
-            );
-            load_textdomain(self::DOMAIN, $dir . 'plugins/' . self::DOMAIN . '-' . $locale . '.mo');
-            load_plugin_textdomain(self::DOMAIN, false, dirname(plugin_basename(__FILE__)) . '/languages');
+
+            load_textdomain(self::DOMAIN, __DIR__ . '/languages/' . self::DOMAIN . '-' . $locale . '.mo');
```
Comment (EdieLemoine) [inline woocommerce-myparcel.php:151]: verander meteen ff die concat dan

**Review by EdieLemoine — CHANGES_REQUESTED** [review]

**Review by EdieLemoine — APPROVED** [review]

**Review by RichardPerdaan — APPROVED** [review]
