### PR TITLE
fix(checkout): show correct prices when switching between shipping methods

### LINKED ISSUE #557: Total price at delivery options depend on selected option at last refresh
**Describe the bug**
I wanted to achieve that for shipments in The Netherlands below 500gr the client can choose between a mailbox package and a normal package, while for shipments over 500gr only a normal package is available. In order to get only delivery options for the package and not for the mailbox package I made 2 shipping rates:
  - Flat rate of 6,50 for packages, coupled to the Package in the MyParcel backend
  - Weight based shipping rate of 4,15 for weights up to 500 gram coupled to the Mailbox in the MyParcel backend.

In principle this works....but, if I get to the checkout the mailbox is by default selected, if I then select the Package the delivery options show, but the total prices in the Delivery options are given are based on the Mailbox price (the total price of the order is correct though). If I then refresh the browser the prices are based on the Package price.
Hence, when a shipping option is chosen that requires the delivery options to be shown, it should grab the correct base price for the correct shipping method. Apparently it now just uses the base price of whatever shipping method was chosen when the checkout was first loaded.

**Steps to reproduce this behaviour**
1. Define to shipping methods with 2 prices. One for mailbox and one for package
2. In Checkout, toggle between the two and refresh the browser (F5 typically).....
3. The total price in the Delivery option changes

**Expected behaviour**
A single price in the Delivery options, not depending on prices of other shipping methods that don't even have Deliver options.

**Screenshots**

**Details**
 - WordPress version: 5.6.1
 - WooCommerce version: 4.9.2
 - WooCommerce MyParcel version: 4.1.5
 - Theme: Storefron Deli.

**Additional context**
Of course this whole issue would be solved if the Delivery options wouldn't give the total price, but just the additional price of the options (hence Standard delivery just being  empty and any other option the additional price).

image

### PR DESCRIPTION
**Pull request by EdieLemoine**
closes #557

### CODE REVIEW

**Review by alexmaat — APPROVED** [review]

File: src/js/wcmp-frontend.js [hunk 1]
```diff
@@ -599,7 +601,28 @@ jQuery(($) => {
...
     /**
-     * @returns {String}
+     * Fetch and update the delivery options config. For use with changing shipping methods, for example, as doing so
+     *  changes the prices of delivery and any extra options.
+     */
+    updateDeliveryOptionsConfig() {
+      MyParcelFrontend.validateMyParcelConfig();
+      $.ajax({
+        type: 'GET',
+        url: wcmp.ajax_url,
```
Comment (mknijnenberg) [inline src/js/wcmp-frontend.js:611]: hanteren we geen `nonce` values?

**Review by mknijnenberg — CHANGES_REQUESTED** [review]

File: src/js/wcmp-frontend.js (hunk 1 above)
Comment (EdieLemoine) [reply src/js/wcmp-frontend.js:611]: (nog) niet in de frontend, nee

**Review by mknijnenberg — APPROVED** [review]
