### PR TITLE
fix ship_to_different_address check in validation

### LINKED ISSUE #578: Shipping address is validated even when not enabled
**Describe the bug**
In this code:
https://github.com/myparcelnl/woocommerce/blob/d94c7c9832c58af1db8825fa26db7f8511c93ace/includes/class-wcmp-postcode-fields.php#L740-L749

the line:
```php
array_key_exists('ship_to_different_address', $address)
```

will evaluate to `true` even when the checkbox is not actually checked, the value being `false`:
xdebug-myparcel-checkout-variables

changing this to:
```php
!empty( $address['ship_to_different_address'] )
```

Will prevent error notices from showing up when the shipping address doesn't pass validation (but would be overwritten by billing address anyway):
vul-een-geldig-verzendadres-in

### PR DESCRIPTION
**Pull request by Spreeuw**
closes #578

### CODE REVIEW

File: includes/class-wcmp-postcode-fields.php [hunk 1]
```diff
@@ -738,7 +738,7 @@ public function validate_address_fields($address, $errors)
         }
 
         if (self::isCountryWithSplitAddressFields($address['shipping_country'])
-            && array_key_exists('ship_to_different_address', $address)
+            && ! empty( $address['ship_to_different_address'] )
```
Comment (EdieLemoine) [inline includes/class-wcmp-postcode-fields.php:741]: Minor code style detail:
```suggestion
            && ! empty($address['ship_to_different_address'])
```

**Review by EdieLemoine — CHANGES_REQUESTED** [review]

**Review by EdieLemoine — APPROVED** [review]

**Review by RichardPerdaan — APPROVED** [review]
