### PR TITLE
fix: allow old shipping methods in order

### LINKED ISSUE #701: Edit a old order gives fatal error and brakes order
I changed an old order, I added it to a customer

And at that moment I got an fatal error of the website caused by this plugin.
Now the order is broken :(

See:
WordPress versie 5.8.1
Huidig thema: Flatsome Child (versie 3.0)
Huidige plugin: WooCommerce MyParcel (versie 4.4.5)
PHP versie 7.3.30

Foutdetails
===========
Een fout van het type E_ERROR werd veroorzaakt op regelnummer 914 van het bestand /home/pahedomotica/public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/class-wcmp-export.php. Foutmelding: Uncaught TypeError: Return value of WCMP_Export::getOrderShippingClass() must be of the type int or null, string returned in /home/pahedomotica/public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/class-wcmp-export.php:914
Stack trace:
#0 /home/pahedomotica/public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/class-wcmp-export.php(958): WCMP_Export->getOrderShippingClass(Object(Automattic\WooCommerce\Admin\Overrides\Order), 'free_shipping:3')
#1 /home/pahedomotica/public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/OrderSettings.php(428): WCMP_Export->getPackageTypeFromOrder(Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(MyParcelNL\Sdk\src\Adapter\DeliveryOptions\DeliveryOptionsV2Adapter))
#2 /home/pahedomotica/public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/OrderSettings.php(234): OrderSettings->setPackageType()
#3 /home/pahedomotica/public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/OrderSettings.php(126): OrderSetti

image

image

### PR DESCRIPTION
**Pull request by joerivanveen**
- Resolves #701

### CODE REVIEW

**Review by RichardPerdaan — APPROVED** [review]

File: includes/admin/class-wcmp-export.php [hunk 1]
```diff
@@ -899,10 +899,10 @@ public function saveShipmentData(WC_Order $order, array $shipment): void
      * @param WC_Order $order
      * @param string   $shippingMethodId
      *
-     * @return int|null
+     * @return string|null
      * @throws Exception
      */
-    public function getOrderShippingClass(WC_Order $order, string $shippingMethodId = ''): ?int
+    public function getOrderShippingClass(WC_Order $order, string $shippingMethodId = '')
```
Comment (EdieLemoine) [inline includes/admin/class-wcmp-export.php:905]: geen `?string`?

**Review by EdieLemoine — CHANGES_REQUESTED** [review]

**Review by RichardPerdaan — DISMISSED** [review]

**Review by EdieLemoine — DISMISSED** [review]

**Review by EdieLemoine — DISMISSED** [review]

**Review by RichardPerdaan — APPROVED** [review]

**Review by EdieLemoine — APPROVED** [review]

**Review by RichardPerdaan — APPROVED** [review]
